import 'package:flutter/material.dart';
import 'package:project/pages/Detail.dart';
import 'package:project/pages/Search.dart';
import 'package:project/pages/Product.dart';
import 'package:project/pages/AccManagement.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Home(),
        ]),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Stack(
          children: [
            Container(
              width: 430,
              height: 932,
              clipBehavior: Clip.antiAlias,
              decoration: BoxDecoration(color: Colors.white),
              child: Stack(
                children: [
                  Positioned(
                    left: -190,
                    top: 538.10,
                    child: Transform(
                      transform: Matrix4.identity()
                        ..translate(0.0, 0.0)
                        ..rotateZ(-0.35),
                      child: Container(
                        width: 194,
                        height: 491,
                        decoration: BoxDecoration(color: Color(0xFFC0C0C0)),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 439.02,
                    top: -194,
                    child: Transform(
                      transform: Matrix4.identity()
                        ..translate(0.0, 0.0)
                        ..rotateZ(0.89),
                      child: Container(
                        width: 249.63,
                        height: 491,
                        decoration: BoxDecoration(color: Color(0xFFFF8C8C)),
                      ),
                    ),
                  ),
                  Positioned(
                    left: -105,
                    top: 71.14,
                    child: Transform(
                      transform: Matrix4.identity()
                        ..translate(0.0, 0.0)
                        ..rotateZ(-1.13),
                      child: Container(
                        width: 194,
                        height: 491,
                        decoration: BoxDecoration(color: Color(0xFFFF0000)),
                      ),
                    ),
                  ),

                  Positioned(
                    top: 150, // Adjust top position as needed
                    left: 18, // Adjust left position as needed
                    child: GestureDetector(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => Search()),
      );
    },
                    child: Container(
                      width: 320, // Adjust width as needed
                      height: 40, // Adjust height as needed
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(10),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.grey.withOpacity(0.5),
                            spreadRadius: 2,
                            blurRadius: 5,
                            offset: Offset(0, 3),
                          ),
                        ],
                      ),
                      child: SingleChildScrollView(
                        padding: const EdgeInsets.symmetric(horizontal: 8.0),
                        child: TextField(
                          decoration: InputDecoration(
                            hintText: 'Search...',
                            hintStyle: TextStyle(color: Colors.black),
                            border: InputBorder.none,
                            suffixIcon: IconButton(
                              icon: Icon(Icons.clear),
                              onPressed: () {
                                // Clear text field
                              },
                            ),
                          ),
                          style: TextStyle(color: Colors.black),
                          onChanged: (value) {
                            // Handle text changes
                          },
                        ),
                      ),
                    ),
                    )
                  ),
                  Positioned(
                    left: 21,
                    top: 20,
                    child: Text(
                      'ByTy',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontStyle: FontStyle.italic,
                        fontFamily: 'Istok Web',
                        fontWeight: FontWeight.w700,
                        height: 0,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: 214,
                    child: Opacity(
                      opacity: 0.41,
                      child: Container(
                        width: 430,
                        height: 297,
                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: 574,
                    child: Opacity(
                      opacity: 0.41,
                      child: Container(
                        width: 430,
                        height: 297,
                        decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                      ),
                    ),
                  ),
                  Positioned(
                    left: -27,
                    top: 261,
                    child: GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(builder: (context) => Product()),
                        );
                      },
                      child: Builder(
                        builder: (context) => Container(
                          width: 137,
                          height: 174,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage("asset/image/home/shoe1.png"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 143,
                    top: 261,
                    child: Container(
                      width: 137,
                      height: 174,
                      decoration: ShapeDecoration(
                        color: Color(0xFFB4B4B4),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 313,
                    top: 261,
                    child: Container(
                      width: 137,
                      height: 174,
                      decoration: ShapeDecoration(
                        color: Color(0xFFB4B4B4),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 483,
                    top: 261,
                    child: Container(
                      width: 137,
                      height: 174,
                      decoration: ShapeDecoration(
                        color: Color(0xFFB4B4B4),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: -3,
                    top: 451,
                    child: Text(
                      'Sneaker',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontStyle: FontStyle.italic,
                        fontFamily: 'Istok Web',
                        fontWeight: FontWeight.w700,
                        height: 0,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 187,
                    top: 446,
                    child: Text(
                      'Pants',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontStyle: FontStyle.italic,
                        fontFamily: 'Istok Web',
                        fontWeight: FontWeight.w700,
                        height: 0,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 349,
                    top: 446,
                    child: Text(
                      'Gadget',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontStyle: FontStyle.italic,
                        fontFamily: 'Istok Web',
                        fontWeight: FontWeight.w700,
                        height: 0,
                      ),
                    ),
                  ),
                  Positioned(
                    left: 523,
                    top: 442,
                    child: Text(
                      'T-shirt',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 20,
                        fontStyle: FontStyle.italic,
                        fontFamily: 'Istok Web',
                        fontWeight: FontWeight.w700,
                        height: 0,
                      ),
                    ),
                  ),
                  Positioned(
                    left: -27,
                    top: 621,
                    child: Container(
                      width: 647,
                      height: 219,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Container(
                            width: 647,
                            height: 219,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 0,
                                  child: Container(
                                    width: 137,
                                    height: 174,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFFB4B4B4),
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 170,
                                  top: 0,
                                  child: Container(
                                    width: 137,
                                    height: 174,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFFB4B4B4),
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 340,
                                  top: 0,
                                  child: Container(
                                    width: 137,
                                    height: 174,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFFB4B4B4),
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 510,
                                  top: 0,
                                  child: Container(
                                    width: 137,
                                    height: 174,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFFB4B4B4),
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 3, color: Color(0xFFFF0000)),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 41,
                                  top: 190,
                                  child: Text(
                                    'Nike',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontStyle: FontStyle.italic,
                                      fontFamily: 'Istok Web',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 204,
                                  top: 185,
                                  child: Text(
                                    'Addidas',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontStyle: FontStyle.italic,
                                      fontFamily: 'Istok Web',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 383,
                                  top: 185,
                                  child: Text(
                                    'Gucci',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontStyle: FontStyle.italic,
                                      fontFamily: 'Istok Web',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 550,
                                  top: 181,
                                  child: Text(
                                    'T-shirt',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontStyle: FontStyle.italic,
                                      fontFamily: 'Istok Web',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 299,
                    top: -38,
                    child: Container(
                      width: 69,
                      height: 142,
                      decoration: ShapeDecoration(
                        color: Color(0xFFD9D9D9),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(15),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 315,
                    top: 10,
                    child: GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,MaterialPageRoute(builder: (context) => AccountmanagementWidget()),
                        );
                      },
                      child: SingleChildScrollView(
                        child: Container(
                          width: 44,
                          height: 44,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image:
                                  AssetImage("asset/image/home/navigate.png"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 315,
                    top: 58,
                    child: GestureDetector(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => Search()),
      );
    },
                    child: Container(
                      width: 33,
                      height: 33,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage("asset/image/home/search.png"),
                          fit: BoxFit.fill,
                        ),
                      ),
                    ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
