// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm1PCVE3A0WpyHaZU7NAjkKmHuCMlYMAE',
    appId: '1:927665042297:web:5d43a84a99e3cc5b9fb5a8',
    messagingSenderId: '927665042297',
    projectId: 'projectphase2-cb03d',
    authDomain: 'projectphase2-cb03d.firebaseapp.com',
    storageBucket: 'projectphase2-cb03d.appspot.com',
    measurementId: 'G-305QM5S5EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzE2Vxr6L4rR_OOCo_SeK1HARqObVYPx8',
    appId: '1:927665042297:android:bdc8fb3fb7cd3df69fb5a8',
    messagingSenderId: '927665042297',
    projectId: 'projectphase2-cb03d',
    storageBucket: 'projectphase2-cb03d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWHhFYW0-uTJYDjNfdJ5LHwtsjZXAHZ9M',
    appId: '1:927665042297:ios:fb145964cb98d0359fb5a8',
    messagingSenderId: '927665042297',
    projectId: 'projectphase2-cb03d',
    storageBucket: 'projectphase2-cb03d.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWHhFYW0-uTJYDjNfdJ5LHwtsjZXAHZ9M',
    appId: '1:927665042297:ios:fb145964cb98d0359fb5a8',
    messagingSenderId: '927665042297',
    projectId: 'projectphase2-cb03d',
    storageBucket: 'projectphase2-cb03d.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm1PCVE3A0WpyHaZU7NAjkKmHuCMlYMAE',
    appId: '1:927665042297:web:bd6aad79d4e4c5699fb5a8',
    messagingSenderId: '927665042297',
    projectId: 'projectphase2-cb03d',
    authDomain: 'projectphase2-cb03d.firebaseapp.com',
    storageBucket: 'projectphase2-cb03d.appspot.com',
    measurementId: 'G-S4FV16TKGX',
  );

}